import type { Config } from "tailwindcss";

// Tokens transcribed directly from DESIGN.md ("Dark Obsidian Cinema").
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1c1b1d",
        "surface-container": "#201f21",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#e6beb2",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        outline: "#ad897e",
        "outline-variant": "#5c4037",
        "surface-tint": "#ffb59e",
        primary: "#ffb59e",
        "on-primary": "#5e1700",
        "primary-container": "#ff571a",
        "on-primary-container": "#521300",
        "inverse-primary": "#ae3200",
        secondary: "#ffb781",
        "on-secondary": "#4e2600",
        "secondary-container": "#ff8a0d",
        "on-secondary-container": "#623000",
        tertiary: "#ffba26",
        "on-tertiary": "#422d00",
        "tertiary-container": "#bd8700",
        "on-tertiary-container": "#392600",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#131315",
        "on-background": "#e5e1e4",
        "surface-variant": "#353437",
        "glass-border": "rgba(255,255,255,0.08)",
      },
      fontFamily: {
        display: ["Readex Pro", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg-mobile": ["44px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6" }],
        "body-md": ["16px", { lineHeight: "1.6" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "120px",
      },
      maxWidth: { content: "1440px" },
      boxShadow: {
        bloom: "0 0 40px 6px rgba(255,87,26,0.35)",
        "bloom-sm": "0 0 20px 3px rgba(255,87,26,0.35)",
      },
      backdropBlur: { modal: "16px" },
    },
  },
  plugins: [],
} satisfies Config;
